GET http://localhost:3000/checkout/order/12312/2342342?bam=wham&wham=Limp HTTP/1.1

###
GET http://localhost:3000/catalog HTTP/1.1


###
POST http://localhost:3000/catalog HTTP/1.1
Content-Type: application/json

{
    "objectIds": ["7RUDIRY47XIZ4Z7GYOMNJLIB"],
    "includeRelatedObjects": true
}